import type { Metadata } from "next";
import "./globals.css";
import { Anybody } from 'next/font/google'

import Header from "./components/Header";
import Tabs from "./components/Tabs";

const anybody = Anybody({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${anybody.className} bg-top-image`}>
        <Header />
        <Tabs />
        {children}
      </body>
    </html>
  );
}
